/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VelodromeGauge } from "./VelodromeGauge";
export type { VelodromePair } from "./VelodromePair";
export * as factories from "./factories";
export { VelodromeGauge__factory } from "./factories/VelodromeGauge__factory";
export { VelodromePair__factory } from "./factories/VelodromePair__factory";
